name: testing
on: push
env:
  CI: false
  REACT_APP_API_BASE_URL: ${{ secrets.BASE_URL }}
jobs:
  unit_and_integration_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
      - name: create env file
        run: |
          touch .env
          echo REACT_APP_API_BASE_URL=${{ secrets.BASE_URL }} >> .env
      - name: Install app dependencies
        run: npm install
      - name: Run the tests
        run: npm test
  e2e_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
      - name: create env file
        # run: |
        # touch .env
        # echo REACT_APP_API_BASE_URL=${{ secrets.BASE_URL }} >> .env
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
