name: testing
on: push

jobs:
  unit_and_integration_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
      - name: create env file
        run: |
          touch .env
          echo REACT_APP_BASE_URL=${{ secrets.BASE_URL }} >> .env
      - name: Install app dependencies
        run: npm install
      - name: Run the tests
        run: npm test
  e2e_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
      - name: create env file
        run: |
          touch .env
          echo REACT_APP_BASE_URL=${{ secrets.BASE_URL }} >> .env
      - name: Install app dependencies
        run: npm install
      #- name: Run the tests
      #  run: npm test
      #- name: Install app dependencies
      #  run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
